create table users
(
    id         bigint generated by default as identity
        constraint users_pkey
            primary key,
    email      varchar(255) not null
        constraint uk_6dotkott2kjsp8vw4d0m25fb7
            unique,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    role       varchar(255),
    status     varchar(255)
);

alter table users
    owner to root;