CREATE TABLE public.contract
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    end_date date,
    start_date date,
    house_id bigint,
    tenant_id bigint,
    CONSTRAINT contract_pkey PRIMARY KEY (id),
    CONSTRAINT fknso1036jrh4bdoryjjwm5ihrq FOREIGN KEY (tenant_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkpxb43re7sw5e9brclue8pxskr FOREIGN KEY (house_id)
        REFERENCES public.house (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE public.contract
    OWNER to root;