create table city
(
    id        bigint generated by default as identity
        constraint city_pkey
            primary key,
    name      varchar(255) not null,
    region_id integer      not null
);

alter table city
    owner to root;

