CREATE TABLE public.house
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    landlord_id bigint NOT NULL,
    outside character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    rooms integer NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    city_id bigint,
    CONSTRAINT house_pkey PRIMARY KEY (id),
    CONSTRAINT fkfin1oycsetvc7uktiniuw5ei6 FOREIGN KEY (city_id)
        REFERENCES public.city (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE public.house
    OWNER to root;