CREATE TABLE public.city
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    region_id integer NOT NULL,
    CONSTRAINT city_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.city
    OWNER to root;