create table contract
(
    id         bigint generated by default as identity
        constraint contract_pkey
            primary key,
    end_date   date,
    start_date date,
    house_id   bigint
        constraint fkpxb43re7sw5e9brclue8pxskr
            references house,
    tenant_id  bigint
        constraint fknso1036jrh4bdoryjjwm5ihrq
            references users
);

alter table contract
    owner to root;