CREATE TABLE public.log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    event character varying(255) COLLATE pg_catalog."default",
    who character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT log_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.log
    OWNER to root;