create table log
(
    id    bigint generated by default as identity
        constraint log_pkey
            primary key,
    event varchar(255),
    who   varchar(255)
);

alter table log
    owner to root;